---
editor: 
  markdown: 
    wrap: 72
---

# Manipuler des fichiers parquets avec duckdb {.backgroundTitre}

## Qu’est-ce que duckdb ?

DuckDB est un projet open-source qui propose un moteur SQL optimisé pour **réaliser des travaux d’analyse statistique sur des bases de données**.  

Plusieurs avantages :  

- Un **moteur portable** utilisable avec **plusieurs langages** (R, Python, Javascript...) et **plusieurs OS** (Windows, Linux, MacOS...)  
- Une **installation** et une **utilisation** très **facile**  

- Un **moteur SQL** capable d'utiliser des <u>données au format Parquet</u> **sans les charger complètement en mémoire**.  


::: callout-note

Il faut bien distinguer le projet DuckDB du package R duckdb qui propose simplement une façon d'utiliser Duckdb avec R.

:::


## À quoi sert le package duckdb ?

Du point de vue d’un statisticien utilisant R, le package duckdb permet de faire trois choses:

- Importer des données (exemples: fichiers CSV, fichiers Parquet)  
- Manipuler des données avec la syntaxe dplyr, ou avec le langage SQL  
- Écrire des données au format Parquet.  

## Alors arrow ou duckdb ?

Tableau repris de la documentation [utilitr](https://book.utilitr.org/)

| Je souhaite...                                                            | arrow | duckdb |
| ------------------------------------------------------------------------- | ----- | ------ |
| Optimiser mes traitements pour des données volumineuses                   | ✔️     | ✔️     |
| Travailler sur un fichier .parquet ou .csv sans le charger entièrement en mémoire | ✔️     | ✔️     |
| Utiliser la syntaxe `dplyr` pour traiter mes données                      | ✔️     | ✔️     |
| Utiliser du langage SQL pour traiter mes données                          | ❌     | ✔️     |
| Joindre des tables très volumineuses (plus de 4 Go)                          | ❌     | ✔️     |
| Utiliser des fonctions fenêtres (voir @sec-arrow)                          | ❌     | ✔️     |
| Utiliser des fonctions statistiques qui n'existent pas dans arrow (voir @sec-arrow) | ❌     | ✔️     |
| Écrire un fichier .parquet                                                | ✔️     | ✔️ *   |
